## stock configuration that works for on raw docker

# pi@raspberrypi:~/openhim-common $ cat docker-compose.yml
# services:
#   mongo:
#     container_name: openhim-mongo
#     ports:
#       - "27017:27017"
#     image: mongo:3.4

#   core:
#     container_name: openhim-core
#     image: jembi/openhim-core
#     environment:
#       - mongo_url=mongodb://mongo/openhim
#       - mongo_atnaUrl=mongodb://mongo/openhim
#     ports:
#       - "8080:8080"
#       - "5000:5000"
#       - "5001:5001"
#       - "5050:5050"
#       - "5051:5051"
#       - "5052:5052"
#       - "7788:7788"
#     depends_on:
#       - mongo

#   console:
#     container_name: openhim-console
#     image: jembi/openhim-console
#     ports:
#         - "9000:80"
#     volumes:
#       - ./default.json:/usr/share/nginx/html/config/default.json

# pi@raspberrypi:~/openhim-common $ cat default.json
# {
#   "version": "1.18.2",
#   "minimumCoreVersion": "5.2.0",
#   "protocol": "https",
#   "host": "localhost",
#   "hostPath": "",
#   "port": "8080",
#   "title": "Admin Console",
#   "footerTitle": "OpenHIM Administration Console",
#   "footerPoweredBy": "<a href='http://openhim.org/' target='_blank'>Powered by OpenHIM</a>",
#   "loginBanner": "",
#   "mediatorLastHeartbeatWarningSeconds": 60,
#   "mediatorLastHeartbeatDangerSeconds": 120,
#   "showLoginForm": true,
#   "ssoEnabled": false,
#   "keyCloakUrl": "http://localhost:9088",
#   "keyCloakRealm": "platform-realm",
#   "keyCloakClientId": "openhim-oauth"
# }


# OpenHIM Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: openhim


#####
# MongoDB
#####
---
# OpenHIM MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhim-mongo
  namespace: openhim
spec:
  selector:
    matchLabels:
      app: openhim-mongo
  template:
    metadata:
      labels:
        app: openhim-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.2
        ports:
        - containerPort: 27017
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "1000m"
---
# OpenHIM MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: openhim-mongo
  namespace: openhim
spec:
  selector:
    app: openhim-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

#####
# CORE
#####
---
# OpenHIM Core Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhim-core
  namespace: openhim
spec:
  selector:
    matchLabels:
      app: openhim-core
  template:
    metadata:
      labels:
        app: openhim-core
    spec:
      containers:
      - name: openhim-core
        image: jembi/openhim-core:latest
        env:
        - name: mongo_url
          value: "mongodb://openhim-mongo/openhim"
        - name: mongo_atnaUrl
          value: "mongodb://openhim-mongo/openhim"
        # - name: NODE_ENV
        #   value: "production"
        - name: NODE_ENV
          value: "development"
        - name: api_trustProxy
          value: "true"
        # - name: api_port
        #   value: "8080"
        # - name: api_authenticationTypes
        #   value: "[\"token\", \"basic\", \"openid\", \"local\"]"
        # - name: authentication_enableCustomTokenAuthentication
        #   value: "true"
        # - name: authentication_enableJWTAuthentication
        #   value: "true"
        # - name: authentication_jwt_secretOrPublicKey
        #   value: "secret"
        # - name: authentication_jwt_algorithms
        #   value: "HS256"
        # - name: authentication_jwt_issuer
        #   value: "openhim"
        - name: openhimConsoleBaseUrl
          value: "https://openhim-console.tail126a09.ts.net"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        ports:
        - containerPort: 8080
        - containerPort: 5000
        - containerPort: 5001
        - containerPort: 5050
        - containerPort: 5051
        - containerPort: 5052
        - containerPort: 7788
        # livenessProbe:
        #   httpGet:
        #     path: /heartbeat
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        #   timeoutSeconds: 30
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /heartbeat
        #     port: 8080
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        #   timeoutSeconds: 30
        #   failureThreshold: 3
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "1000m"
---
# OpenHIM Core Service
apiVersion: v1
kind: Service
metadata:
  name: openhim-core
  namespace: openhim
spec:
  type: NodePort
  selector:
    app: openhim-core
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: https-5000
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
    - name: https-5001
      protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30501
    - name: https-5050
      protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 30550
    - name: https-5051
      protocol: TCP
      port: 5051
      targetPort: 5051
      nodePort: 30551
    - name: https-5052
      protocol: TCP
      port: 5052
      targetPort: 5052
      nodePort: 30552
    - name: https-7788
      protocol: TCP
      port: 7788
      targetPort: 7788
      nodePort: 30778
---
#####
# CONSOLE
#####
---
# OpenHIM Console Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhim-console
  namespace: openhim
spec:
  selector:
    matchLabels:
      app: openhim-console
  template:
    metadata:
      labels:
        app: openhim-console
    spec:
      containers:
      - name: openhim-console
        image: jembi/openhim-console:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 3
        resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/config/default.json
          subPath: default.json
      volumes:
      - name: config-volume
        configMap:
          name: openhim-console-config
---
# OpenHIM Console ConfigMap for default.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: openhim-console-config
  namespace: openhim
data:
  default.json: |
    {
      "version": "1.10.3",
      "minimumCoreVersion": "5.2.0",
      "protocol": "https",
      "host": "openhim.local",
      "port": "",
      "title": "Admin Console",
      "footerTitle": "OpenHIM Administration Console",
      "footerPoweredBy": "<a href='http://openhim.org/' target='_blank'>Powered by OpenHIM</a>",
      "loginBanner": "",
      "mediatorLastHeartbeatWarningSeconds": 60,
      "mediatorLastHeartbeatDangerSeconds": 120,
      "showLoginForm": true
    }
---
# OpenHIM Console Service
apiVersion: v1
kind: Service
metadata:
  name: openhim-console
  namespace: openhim
spec:
  selector:
    app: openhim-console
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
---
# OpenHIM Console Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openhim-console-ingress
  namespace: openhim
  labels:
    app.kubernetes.io/name: openhim-console
    app.kubernetes.io/component: ingress
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
      - openhim-console
  rules:
    - host: openhim-console
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openhim-console
                port:
                  number: 9000
---
# OpenHIM Core Ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openhim-core-ingress
  namespace: openhim
  labels:
    app.kubernetes.io/name: openhim-core
    app.kubernetes.io/component: ingress
  annotations:
    # Traefik-specific annotations for TLS (if using Let's Encrypt)
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
      - openhim.raspberrypi.tail126a09.ts.net
  rules:
    - host: openhim.raspberrypi.tail126a09.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openhim-core
                port:
                  number: 5001
