---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: "1.16.9"
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
  values:
    # Deployment configuration
    n8n:
      replicaCount: 1

      image:
        repository: n8nio/n8n
        tag: "1.49.0"  # Using a recent stable version
        pullPolicy: IfNotPresent

      # Resource limits (adjusted for Raspberry Pi)
      # resources:
      #   limits:
      #     cpu: "1000m"
      #     memory: "2Gi"
      #   requests:
      #     cpu: "500m"
      #     memory: "1Gi"

      # Service configuration - adjusted to match chart schema
      service:
        type: ClusterIP
        port: 5678
        # Removed targetPort as it's not allowed in this version
        annotations: {}

      # Persistence for n8n data
      persistence:
        enabled: true
        size: 5Gi
        storageClass: null  # Uses default storage class (local-path on K3s)

      # Environment variables
      # Using extraEnvs instead of env to match the chart schema
      config:
        N8N_BASIC_AUTH_ACTIVE: "false"
        N8N_METRICS: "true"
        N8N_LOG_LEVEL: "info"

    # Ingress configuration
    ingress:
      enabled: true
      className: "tailscale"
      annotations:
        tailscale.com/expose: "true"
      hosts:
        - host: n8n
          paths:
            - path: /
              pathType: Prefix
      tls: []

    # Database configuration (using SQLite by default, can be changed to PostgreSQL if needed)
    postgresql:
      enabled: false  # Disabled to use SQLite for simplicity in this deployment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: default
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: ingress
  annotations:
    tailscale.com/expose: "true"
spec:
  ingressClassName: tailscale
  rules:
    - host: n8n
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678
  tls:
    - hosts:
        - n8n