---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: n8n
      version: "1.16.9"
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
  values:
    # Image configuration at top level
    image:
      repository: n8nio/n8n
      tag: "stable"  # Using a recent stable version
      pullPolicy: IfNotPresent

    # Service configuration at top level
    service:
      type: ClusterIP
      port: 5678
      name: http
      annotations: {}

    # Main node configuration
    main:
      count: 1
      persistence:
        enabled: true
        size: 5Gi
        mountPath: "/home/node/.n8n"
        annotations:
          helm.sh/resource-policy: keep
      extraEnvVars:
        N8N_BASIC_AUTH_ACTIVE: "false"
        N8N_METRICS: "true"
        N8N_LOG_LEVEL: "info"
        N8N_HIRING_BANNER_ENABLED: "false"

    # Ingress configuration
    ingress:
      enabled: true
      className: "tailscale"
      annotations:
        tailscale.com/expose: "true"
      hosts:
        - host: n8n
          paths:
            - path: /
              pathType: Prefix
      tls: []

    # Database configuration
    db:
      type: sqlite

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: default
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: ingress
  annotations:
    tailscale.com/expose: "true"
spec:
  ingressClassName: tailscale
  rules:
    - host: n8n
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678
  tls:
    - hosts:
        - n8n