# clusters/pi-cluster/infrastructure/headlamp-tls-secret.yaml
# Self-signed certificate for Headlamp (alternative to Tailscale auto-cert)
# This provides a fallback option if Tailscale certificate management doesn't work

---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-tls-cert
  namespace: headlamp
type: kubernetes.io/tls
# To create this secret, run the following commands:
# 1. Generate a self-signed certificate:
#    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#      -keyout headlamp.key -out headlamp.crt \
#      -subj "/CN=headlamp/O=headlamp" \
#      -addext "subjectAltName = DNS:headlamp,DNS:headlamp.tail126a09.ts.net"
#
# 2. Create the Kubernetes secret:
#    kubectl create secret tls headlamp-tls-cert \
#      --namespace headlamp \
#      --cert=headlamp.crt \
#      --key=headlamp.key
#
# Note: You'll need to replace "tail126a09.ts.net" with your actual Tailscale domain
# The certificate will be self-signed, so you'll need to trust it in your browser
# or use the Tailscale certificate management approach instead.