# clusters/pi-cluster/infrastructure/headlamp.yaml

---
apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
---
# Service Account for Headlamp authentication
# kubectl -n kube-system create serviceaccount headlamp-admin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin
  namespace: headlamp
---
# ClusterRoleBinding to grant admin access to Headlamp ServiceAccount
# kubectl create clusterrolebinding headlamp-admin --serviceaccount=kube-system:headlamp-admin --clusterrole=cluster-admin
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
subjects:
- kind: ServiceAccount
  name: headlamp-admin
  namespace: headlamp
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      version: "0.38.0"  # Using the latest stable version
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  values:
    # Headlamp configuration based on official Flux plugin documentation
    service:
      type: ClusterIP
      port: 4700
    
    # Flux plugin configuration using initContainer approach
    config:
      pluginsDir: /build/plugins
      # Configure Headlamp to use ServiceAccount token authentication
      # This allows automatic token-based authentication without manual kubectl commands
      enableDynamicPlugins: true
      clusterName: "pi-cluster"
      # Enable in-cluster config for automatic service account token mounting
      inCluster: true
    
    # Init container to install Flux plugin
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    
    # Volume configuration for plugin persistence
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 1Gi
    
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp
      # Mount the ServiceAccount token for automatic authentication
      # - name: headlamp-token
      #   secret:
      #     secretName: headlamp-admin-token
      #     optional: false
    
    # Resource limits (optional)
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    
    # Disable built-in ingress as we handle it separately
    ingress:
      enabled: false

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp-ingress
  namespace: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/component: ingress
  # annotations:
  #   # Enable Tailscale's automatic certificate management
  #   tailscale.com/cert: "true"
  #   # Use the Tailscale MagicDNS domain for the certificate
  #   tailscale.com/cert-domain: "headlamp"
  #   # Enable HTTPS (Tailscale will handle the certificate automatically)
  #   tailscale.com/https: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
      - headlamp
    # Tailscale will automatically provide the certificate for this host
    # No need to specify a secretName as Tailscale handles it
  rules:
    - host: headlamp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headlamp
                port:
                  number: 4700