# clusters/pi-cluster/infrastructure/headlamp.yaml

---
apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 5m
  chart:
    spec:
      chart: headlamp
      version: "0.19.0"  # Using the latest stable version
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  values:
    # Headlamp configuration based on official Flux plugin documentation
    service:
      type: ClusterIP
      port: 80
    
    # Flux plugin configuration using initContainer approach
    config:
      pluginsDir: /build/plugins
    
    # Init container to install Flux plugin
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    
    # Volume configuration for plugin persistence
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 1Gi
    
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp
    
    # Resource limits (optional)
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    
    # Disable built-in ingress as we handle it separately
    ingress:
      enabled: false

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp-ingress
  namespace: headlamp
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/component: ingress
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
      - headlamp
  rules:
    - host: headlamp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headlamp
                port:
                  number: 80