# Create the namespace first
# kubectl create namespace tailscale

# Create the secret with your credentials
# kubectl create secret generic operator-oauth \
#   --namespace tailscale \
#   --from-literal=client-id="<YOUR_CLIENT_ID_HERE>" \
#   --from-literal=client-secret="<YOUR_CLIENT_SECRET_HERE>"

---

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 1h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: tailscale-operator
      version: "1.76.1"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  targetNamespace: tailscale
  install:
    createNamespace: true
  values:
    oauth:
      secretName: operator-oauth
      secretNamespace: tailscale