---
# OpenSRP Community Charts (Contains OpenHIM, HAPI FHIR)
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: opensrp
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.smartregister.org
---
# HAPI FHIR (Alternative/Specific chart if needed, but OpenSRP often covers it)
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: chgl
  namespace: flux-system
spec:
  interval: 1h
  url: https://chgl.github.io/charts
---
# Community Charts (Contains n8n)
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: community-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://community-charts.github.io/helm-charts
---
# Headlamp (Kubernetes Web UI)
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: headlamp
  namespace: flux-system
spec:
  interval: 1h
  url: https://headlamp-k8s.github.io/headlamp-helm/