apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 1h
  url: https://pajikos.github.io/home-assistant-helm-chart
