# clusters\pi-cluster\flux-system\openhie-apps\02-hapi-fhir-release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hapi-fhir-jpaserver
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/hapi-fhir-jpaserver
      version: "0.21.0"
      sourceRef:
        kind: GitRepository
        name: hapi-fhir-starter
        namespace: flux-system
  values:
    replicaCount: 1

    # -------------------------------------------------------------------
    # 1. HAPI FHIR IMAGE CONFIGURATION
    # -------------------------------------------------------------------
    image:
      repository: hapiproject/hapi
      tag: "v8.6.0-1"
      pullPolicy: IfNotPresent

    # -------------------------------------------------------------------
    # 2. RESOURCE LIMITS
    # -------------------------------------------------------------------
    resources:
      requests:
        cpu: "500m"        # half a core minimum
        memory: "4Gi"      # minimum memory for JPA server
      limits:
        cpu: "2"           # allow up to 2 cores
        memory: "8Gi"      # cap memory at 8 GB

    # -------------------------------------------------------------------
    # 3. HEALTH CHECKS - CRITICAL FIX
    # -------------------------------------------------------------------
    startupProbe:
      httpGet:
        path: /fhir/metadata
        port: 8080
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 30  # Allow up to 5 minutes for startup (30 * 10s)

    readinessProbe:
      httpGet:
        path: /fhir/metadata
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3

    livenessProbe:
      httpGet:
        path: /fhir/metadata
        port: 8080
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3

    # -------------------------------------------------------------------
    # 4. POSTGRES CONFIG
    # -------------------------------------------------------------------
    postgresql:
      enabled: true
      architecture: standalone
      image:
        registry: docker.io
        repository: bitnami/postgresql
        tag: "latest"
      auth:
        username: postgres
        password: "password"
        database: fhir
      primary:
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      persistence:
        enabled: true
        size: 20Gi
        storageClass: null

    # -------------------------------------------------------------------
    # 5. SERVICE SETTINGS
    # -------------------------------------------------------------------
    service:
      type: ClusterIP
      port: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hapi-fhir-ingress
  namespace: default
  # annotations:
  #   # For Tailscale ingress, you may need these annotations
  #   tailscale.com/funnel: "true"  # Optional: enables Tailscale Funnel
  labels:
    app.kubernetes.io/name: hapi-fhir-jpaserver
    app.kubernetes.io/component: ingress
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
      - cdr
  rules:
    - host: cdr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hapi-fhir-jpaserver
                port:
                  number: 8080
