# clusters\pi-cluster\flux-system\openhie-apps\02-hapi-fhir-release.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hapi-fhir-jpaserver
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: hapi-fhir-jpaserver
      # FIX 1: Updated version to match the Chart.yaml (was 0.5.x)
      version: "0.21.0"
      sourceRef:
        kind: HelmRepository
        name: chgl
        namespace: flux-system

  values:
    replicaCount: 1

    # -------------------------------------------------------------------
    # 1. HAPI FHIR IMAGE CONFIGURATION
    # -------------------------------------------------------------------
    image:
      # FIX 2: Updated to official HAPI project repo
      repository: hapiproject/hapi
      # FIX 3: Using specific version 'v8.6.0-1' (matches 'latest' but is safer)
      # This tag explicitly supports ARM64 (Raspberry Pi)
      tag: "v8.6.0-1"
      pullPolicy: IfNotPresent

    # -------------------------------------------------------------------
    # 2. RESOURCE LIMITS
    # -------------------------------------------------------------------
    resources:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"

    # -------------------------------------------------------------------
    # 3. POSTGRES CONFIG
    # -------------------------------------------------------------------
    postgresql:
      enabled: true
      architecture: standalone
      image:
        registry: docker.io
        repository: bitnami/postgresql
        # FIX 4: Using 'latest' to ensure ARM64 support (missing in 15.6.0)
        tag: "latest"
      auth:
        username: postgres
        password: "password"
        database: fhir
      primary:
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      persistence:
        enabled: true
        size: 20Gi
        storageClass: null

    # -------------------------------------------------------------------
    # 4. SERVICE SETTINGS
    # -------------------------------------------------------------------
    service:
      type: ClusterIP
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hapi-fhir-ingress
  namespace: default
  labels:
    app.kubernetes.io/name: hapi-fhir-jpaserver
    app.kubernetes.io/component: ingress
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
      - cdr
  rules:
    - host: cdr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hapi-fhir-jpaserver
                port:
                  number: 8080
---